## Adjust Data

In [42]:
#import libraries
import pandas as pd
import numpy as np
import os

In [43]:
#import data
combinedF = os.path.join("C:/Users/jpcor/GoogleDrive/Data Science/Clauset's/PCR Analysis/UncleanedData/TestRaw/", "TESTredo_VanessaPCR_Reaction_Collection_4-9-21.csv")  #"TEST2A_VanessaPCR_Reaction_Collection_3-29-21.csv"
PCR_Data = pd.read_csv(combinedF)

## Data Setup

In [44]:
PCR_Data

,timestamp,user,email,species,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,pcrid,...,template_type,dna_amt_units,wrong_bands,right_band,no_bands,band_size_units,customized_salts,buffer,dmso_amount,notes
0,04/09/2021 14:31:50,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,cDNA,μg,False,True,False,bp,False,NaN,NaN,NaN
1,04/09/2021 14:35:03,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,cDNA,μg,False,True,False,bp,False,NaN,NaN,NaN
2,04/09/2021 14:48:50,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,Plasmid,μg,False,True,False,bp,False,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
#Drop duplicate data 10/26/20
print('before dropping duplicates',len(PCR_Data))
PCR_Data.drop_duplicates(keep='first',inplace=True)
print('after dropping duplicates',len(PCR_Data))

before dropping duplicates 9
after dropping duplicates 4

#Fix polymerase name
PCR_Data['polymerase_name']=PCR_Data['polymerase_name'].apply(lambda x: 'PhusionHF')

In [46]:
PCR_Data

,timestamp,user,email,species,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,pcrid,...,template_type,dna_amt_units,wrong_bands,right_band,no_bands,band_size_units,customized_salts,buffer,dmso_amount,notes
0,04/09/2021 14:31:50,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,cDNA,μg,False,True,False,bp,False,NaN,NaN,NaN
1,04/09/2021 14:35:03,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,cDNA,μg,False,True,False,bp,False,NaN,NaN,NaN
2,04/09/2021 14:48:50,Vanessa Lamae Bauer DuMont,vaba7447@colorado.edu,aotus azarae,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5 High-Fidelity DNA Polymerase,alison's,...,Plasmid,μg,False,True,False,bp,False,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
#Drop unnecessary columns
remove=["timestamp","user","email","species","polymerase_catalog_number","pcrid",
        "template_type","polymerase_brand","dna_amt_units","band_size_units",'customized_salts']
PCR_Data.drop(remove,axis=1,inplace=True)

In [48]:
PCR_Data=PCR_Data.head(len(PCR_Data)-1).copy(deep=True)

In [49]:
PCR_Data

,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,t1_min,temp1,cycles1,melting_t2_min,melting_temp2,...,melting_t2_sec,annealing_t2_sec,extension_t2_sec,t5_sec,wrong_bands,right_band,no_bands,buffer,dmso_amount,notes
0,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,0.0,98.0,1.0,0.0,98.0,...,10.0,30.0,0.0,0.0,False,True,False,NaN,NaN,NaN
1,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,0.0,98.0,1.0,0.0,98.0,...,10.0,30.0,0.0,0.0,False,True,False,NaN,NaN,NaN
2,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5 High-Fidelity DNA Polymerase,0.0,98.0,1.0,0.0,98.0,...,10.0,30.0,0.0,0.0,False,True,False,NaN,NaN,NaN

## Set Outcomes

In [50]:
#Drop original output columns
remove=["wrong_bands","right_band","no_bands"]
PCR_Data.drop(remove,axis=1,inplace=True)

### Data Cleaning

In [51]:
#rename incorrect column labels to correct column labels
PCR_Data.rename(columns={'extension_t2_min.1':'extension_t2_sec','t5_sec':'t3_sec'},inplace=True)

In [52]:
#Convert time inputs to seconds
PCR_Data["t1(sec)"] = (PCR_Data["t1_min"]*60) + PCR_Data["t1_sec"]
PCR_Data["melting_t2(sec)"] = (PCR_Data["melting_t2_min"]*60) + PCR_Data["melting_t2_sec"]
PCR_Data["annealing_t3(sec)"] = (PCR_Data["annealing_t2_min"]*60) + PCR_Data["annealing_t2_sec"]
PCR_Data["extension_t4(sec)"] = (PCR_Data["extension_t2_min"]*60) + PCR_Data["extension_t2_sec"]
PCR_Data["t5(sec)"] = (PCR_Data["t3_min"]*60) + PCR_Data["t3_sec"]

In [53]:
#drop old time columns
remove=["t1_min","t1_sec","melting_t2_min","melting_t2_sec","annealing_t2_min",
        "annealing_t2_sec","extension_t2_min","extension_t2_sec","t3_min","t3_sec"]
PCR_Data.drop(remove,axis=1,inplace=True)

In [54]:
PCR_Data

,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,temp1,cycles1,melting_temp2,annealing_temp2,extension_temp2,...,band_size,dna_amt,buffer,dmso_amount,notes,t1(sec),melting_t2(sec),annealing_t3(sec),extension_t4(sec),t5(sec)
0,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,98.0,1.0,98.0,58.0,72.0,...,1840.0,3.0,NaN,NaN,NaN,30.0,10.0,30.0,60.0,120.0
1,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5 High-Fidelity DNA Polymerase,98.0,1.0,98.0,66.0,72.0,...,1423.0,3.0,NaN,NaN,NaN,30.0,10.0,30.0,60.0,120.0
2,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5 High-Fidelity DNA Polymerase,98.0,1.0,98.0,67.0,72.0,...,2453.0,3.0,NaN,NaN,NaN,30.0,10.0,90.0,60.0,120.0

## Feature Engineering

In [55]:
from Bio.SeqUtils import MeltingTemp as mt
from Bio.SeqUtils import GC
import primer3 as pr
import melting as melt
from NickFunctions import*

In [56]:
def Tm(primer,polymerase,primerconc, option,primer2='NA'):
    '''
    
    
    Description:
    ------------
    Calculates primer melting temperature (Tm) based on a variety of options. Uilizes Buffer function to lookup salt concentrations for each function. Multiple options for testing.
     NOTE: primer2 only necessary when calculating heterodimer
    Options (default 3): 
    1 - Primer3 melting temperature
    2 - Tm_NN BioSeqUtils
    3 - melting (Virtually the same as IDT)
    4 - Hairpin
    5 - Homodimer
    6 - Heterodimer need to input primer2
    
    Differences:

    IDT unsure what NN method is used for calculation. Should use Owczarzy (2008) salt correction.

    Primer3 uses santaLucia (1997) correction. Uses Owczarzy (2008) salt correction

    BioSeqUtils uses santaLucia (2004) review correction. Uses Owczarzy (2008) salt correction
    
    Parameters:
    ------------
    primer, str: primer to calculate melting temperature for
    polymerase, str: simplified polyerase name from "ChangeName" function. Used for lookup table of salt concentrations.
    primerconc, float: from user input
    option, int: melting temp prediction option
    primer2, str: only needed for heterodimer calculation option.
    
    Return:
    ------------
    calculated melting temperature as float.
    '''
    
    b=Buffer(polymerase)#salts in each polymerase buffer
    Tms=[]
    if (option==1):
        return pr.calcTm(seq=primer,
                                    mv_conc=b['MV_tot'],
                                    dv_conc=b['DV_tot'],
                                    dntp_conc=b['dNTPs'],
                                    dna_conc=primerconc,
                                    max_nn_length=60,
                                    tm_method='santalucia',
                                    salt_corrections_method=2)
    elif (option==2):
        return mt.Tm_NN(seq=primer,
                                    nn_table=mt.DNA_NN4,
                                    dnac1=primerconc,
                                    dnac2=0,
                                    Na=b['Na'], 
                                    K=b['K'],
                                    Tris=b['Tris'],
                                    Mg=b['Mg'],
                                    dNTPs=b['dNTPs'],
                                    saltcorr=7)
    elif (option==3):
        return melt.temp(primer,
                                    DNA_c=primerconc,
                                    Na_c=b['MV_tot'],
                                    Mg_c=b['DV_tot'],
                                    dNTPs_c=b['dNTPs'])
    elif (option==4):
        return pr.calcHairpin(seq=primer,
                                    mv_conc=b['MV_tot'],
                                    dv_conc=b['DV_tot'],
                                    dntp_conc=b['dNTPs'],
                                    dna_conc=primerconc,
                                    temp_c=37,
                                    max_loop=30,
                                    output_structure=False).tm
    elif (option==5):
        return pr.calcHomodimer(seq=primer,
                                    mv_conc=b['MV_tot'],
                                    dv_conc=b['DV_tot'],
                                    dntp_conc=b['dNTPs'],
                                    dna_conc=primerconc,
                                    temp_c=37,
                                    max_loop=30,
                                    output_structure=False).tm
    elif (option==6):
        return pr.calcHeterodimer(seq1=primer, seq2=primer2,
                                    mv_conc=b['MV_tot'],
                                    dv_conc=b['DV_tot'],
                                    dntp_conc=b['dNTPs'],
                                    dna_conc=primerconc,
                                    temp_c=37,
                                    max_loop=30,
                                    output_structure=False).tm
    else:
        print("Not a valid option. Please input 1,2,3,4,5, or 6")
        return 0

In [57]:
#Change polymerase name to generalized form for Buffer dictionary
PCR_Data["polymerase_name"]=PCR_Data['polymerase_name'].apply(lambda x: ChangeName(x))
#PCR_Data=PCR_Data.head(1).copy(deep=True)

In [58]:
PCR_Data

,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,temp1,cycles1,melting_temp2,annealing_temp2,extension_temp2,...,band_size,dna_amt,buffer,dmso_amount,notes,t1(sec),melting_t2(sec),annealing_t3(sec),extension_t4(sec),t5(sec)
0,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5,98.0,1.0,98.0,58.0,72.0,...,1840.0,3.0,NaN,NaN,NaN,30.0,10.0,30.0,60.0,120.0
1,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5,98.0,1.0,98.0,66.0,72.0,...,1423.0,3.0,NaN,NaN,NaN,30.0,10.0,30.0,60.0,120.0
2,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5,98.0,1.0,98.0,67.0,72.0,...,2453.0,3.0,NaN,NaN,NaN,30.0,10.0,90.0,60.0,120.0

In [59]:
#Strip blank spaces from primers
PCR_Data["primer1"] = PCR_Data["primer1"].apply(lambda x: x.replace(' ',''))# remove all white space including middle of string
PCR_Data["primer2"] = PCR_Data["primer2"].apply(lambda x: x.replace(' ',''))# remove all white space including middle of string
#Ensure all primers are upper case
PCR_Data["primer1"] = PCR_Data["primer1"].apply(lambda x: x.upper())
PCR_Data["primer2"] = PCR_Data["primer2"].apply(lambda x: x.upper())

In [60]:
#Add Primer GC content
PCR_Data["primer1_GC"] = PCR_Data["primer1"].apply(lambda x: GC(x))
PCR_Data["primer2_GC"] = PCR_Data["primer2"].apply(lambda x: GC(x))

In [61]:
#Add Primer Lengths
PCR_Data["P1_len"] = PCR_Data["primer1"].apply(lambda x: len(x))
PCR_Data["P2_len"] = PCR_Data["primer2"].apply(lambda x: len(x))
#Remove primers with length greater than 60 bioinformatics algorithms do not work well when greater than 60
longPs = PCR_Data[(PCR_Data["P1_len"]>60) | (PCR_Data["P2_len"]>60)].index 
PCR_Data.drop(longPs,inplace=True)

In [62]:
PCR_Data

,primer1,primer2,amtprimer1,amtprimer2,polymerase_name,temp1,cycles1,melting_temp2,annealing_temp2,extension_temp2,...,notes,t1(sec),melting_t2(sec),annealing_t3(sec),extension_t4(sec),t5(sec),primer1_GC,primer2_GC,P1_len,P2_len
0,CAGAAAAGTAACATCCTAGAC,GTTCCGTTGTGTCATCAGG,0.5,0.5,Q5,98.0,1.0,98.0,58.0,72.0,...,NaN,30.0,10.0,30.0,60.0,120.0,38.095238,52.631579,21,19
1,TGCACCCACTGTCTTCC,AGGTCTTGCCGAAACAGATG,0.5,0.5,Q5,98.0,1.0,98.0,66.0,72.0,...,NaN,30.0,10.0,30.0,60.0,120.0,58.823529,50.000000,17,20
2,GATGGGTGGCAAGTGGTC,AAGTTGACCAGTGCCGTTCC,0.5,0.5,Q5,98.0,1.0,98.0,67.0,72.0,...,NaN,30.0,10.0,90.0,60.0,120.0,61.111111,55.000000,18,20

def tep(x):
    return 'PhusionHF'
PCR_Data['polymerase_name']=PCR_Data['polymerase_name'].apply(lambda x: tep(x))

In [63]:
#Add Primer melting temps
#Primer 3 no correction original model
PCR_Data["Tm_p1_p3orig"]=PCR_Data.apply(lambda x: pr.calcTm(x.primer1),axis=1)
PCR_Data["Tm_p2_p3orig"]=PCR_Data.apply(lambda x: pr.calcTm(x.primer2),axis=1)
#Primer3
PCR_Data["Tm_p1_p3"]=PCR_Data.apply(lambda x: Tm(primer=x.primer1,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=1),axis=1)
PCR_Data["Tm_p2_p3"]=PCR_Data.apply(lambda x: Tm(primer=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=1),axis=1)
#BioseqUtils
PCR_Data["Tm_p1_BSU"]=PCR_Data.apply(lambda x: Tm(primer=x.primer1,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=2),axis=1)
PCR_Data["Tm_p2_BSU"]=PCR_Data.apply(lambda x: Tm(primer=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=2),axis=1)
#Melting (IDT analog)
PCR_Data["Tm_p1_IDT"]=PCR_Data.apply(lambda x: Tm(primer=x.primer1,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=3),axis=1)
PCR_Data["Tm_p2_IDT"]=PCR_Data.apply(lambda x: Tm(primer=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=3),axis=1)
#Average
#PCR_Data["Tm_p1_Avg"]=(PCR_Data["Tm_p1_p3"]+PCR_Data["Tm_p1_BSU"]+PCR_Data["Tm_p1_IDT"])/3
#PCR_Data["Tm_p2_Avg"]=(PCR_Data["Tm_p2_p3"]+PCR_Data["Tm_p2_BSU"]+PCR_Data["Tm_p2_IDT"])/3

In [64]:
#difference in primer melting temps
PCR_Data["Tm_dif_IDT"]=abs(PCR_Data["Tm_p1_IDT"]-PCR_Data["Tm_p2_IDT"])

In [65]:
#Add if hairpin structure is predicted
PCR_Data["HP_P1"] = PCR_Data.apply(lambda x: Tm(primer=x.primer1,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=4),axis=1)
PCR_Data["HP_P2"] = PCR_Data.apply(lambda x: Tm(primer=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=4),axis=1)

In [66]:
#Combine hairpins to one feature that has the highest hairpin temp
#if first statement is true return 2nd value first statement is false return third value.
PCR_Data["HPin_Tm_Max"] = np.where(PCR_Data["HP_P1"]>PCR_Data["HP_P2"],PCR_Data["HP_P1"],PCR_Data["HP_P2"])

In [67]:
(PCR_Data.size)/len(PCR_Data.columns)

3.0

**Note**

May want to test how setting any negative values to 0 affects performance.

In [68]:
#Calculate Heterodimer
PCR_Data["Heterodimer_tm"] = PCR_Data.apply(lambda x : Tm(primer=x.primer1,primer2=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=6),axis=1)

In [69]:
#Calculate Homodimer
PCR_Data["Homodimer_tm1"] = PCR_Data.apply(lambda x : Tm(primer=x.primer1,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=5),axis=1)
PCR_Data["Homodimer_tm2"] = PCR_Data.apply(lambda x : Tm(primer=x.primer2,polymerase=x.polymerase_name,primerconc=(x.amtprimer1+x.amtprimer2),option=5),axis=1)
PCR_Data["Homodimer_maxTm"] = np.where(PCR_Data["Homodimer_tm1"]>PCR_Data["Homodimer_tm2"],PCR_Data["Homodimer_tm1"],PCR_Data["Homodimer_tm2"])
PCR_Data["Homodimer_minTm"] = np.where(PCR_Data["Homodimer_tm1"]<PCR_Data["Homodimer_tm2"],PCR_Data["Homodimer_tm1"],PCR_Data["Homodimer_tm2"])

In [70]:
def changeTm(Tm):
    '''
    Tms of less than or equal to zero mean there was no significant structure. To help the RF make these temps all 0
    '''
    if Tm <0:
        return 0
    else:
        return Tm
PCR_Data["Homodimer_maxTm"]=PCR_Data["Homodimer_maxTm"].apply(lambda x: changeTm(x))
PCR_Data["Heterodimer_tm"]=PCR_Data["Heterodimer_tm"].apply(lambda x: changeTm(x))

In [71]:
PCR_Data['MaxTm_IDT']=np.where(PCR_Data["Tm_p1_IDT"]>PCR_Data["Tm_p2_IDT"],PCR_Data["Tm_p1_IDT"],PCR_Data["Tm_p2_IDT"])
PCR_Data['MinTm_IDT']=np.where(PCR_Data["Tm_p1_IDT"]<PCR_Data["Tm_p2_IDT"],PCR_Data["Tm_p1_IDT"],PCR_Data["Tm_p2_IDT"])
PCR_Data['MaxGC']=np.where(PCR_Data["primer1_GC"]>PCR_Data["primer2_GC"],PCR_Data["primer1_GC"],PCR_Data["primer2_GC"])
PCR_Data['MinGC']=np.where(PCR_Data["primer1_GC"]<PCR_Data["primer2_GC"],PCR_Data["primer1_GC"],PCR_Data["primer2_GC"])
PCR_Data['MaxPlen']=np.where(PCR_Data["P1_len"]>PCR_Data["P2_len"],PCR_Data["P1_len"],PCR_Data["P2_len"])
PCR_Data['MinPlen']=np.where(PCR_Data["P1_len"]<PCR_Data["P2_len"],PCR_Data["P1_len"],PCR_Data["P2_len"])
PCR_Data['TotPrimer']=PCR_Data['amtprimer1']+PCR_Data['amtprimer2']

**GC Clamp:**

According to Top Tip Bio (TTP) (https://toptipbio.com/gc-clamp-pcr/) GC Clamp is defined by a G or C in the last 5 nucleotides on the 3' end of the primer.

Strength table for NN model taken from Khandelwahl 2010

In [72]:
class GC_Clamp_features(object):
    '''
    Description:
    ------------
    Class obtains features from GC clamp such as strength and num_GC 
    NN model strength table taken from 
    Khandelwal G, Bhyravabhotla J. A Phenomenological Model for Predicting Melting Temperatures of DNA Sequences. PLOS ONE. 2010;5: e12433. doi:10.1371/journal.pone.0012433
    '''
    #initialize class variables
    clamp = ""
    num_GC = 0
    Strength={'GC': 13,'CC': 11,'GG': 11,'CG': 10,'AC': 10,'TC': 8,'AG': 8,'TG': 7,'GT': 10,'CT': 8,'GA': 8,'CA': 7,'AT': 7,'TT': 5,'AA': 5,'TA': 4}
    Score=0
    #GC_Clamp class constructor
    def __init__(self,primer):
        self.clamp = primer[-5:]
        for nt in range(len(self.clamp)-1):#inrement by 1 nucleotide at a time
            NN=self.clamp[nt]+self.clamp[nt+1]#grab dinucleotides
            self.Score+=self.Strength[NN]#GC clamp strength score
        for nt in range(len(self.clamp)):
            if self.clamp[nt]=="G" or self.clamp[nt]=="C":
                self.num_GC+=1

In [73]:
clamp = GC_Clamp_features("ATACGTACGATAGCA")
print(clamp.clamp)
print(clamp.num_GC)
print(clamp.Score)

TAGCA
2
32

In [74]:
#Create GC_Clamp_features Score
PCR_Data["GC_Clamp1"] = PCR_Data["primer1"].apply(lambda x: GC_Clamp_features(x).Score)
PCR_Data["GC_Clamp2"] = PCR_Data["primer2"].apply(lambda x: GC_Clamp_features(x).Score)

Finalize GC_Clamp features

In [75]:
#Take the lowest GC in clamp and positional weight for p1 and p2
PCR_Data["GC_ClampMin"] = np.where(PCR_Data["GC_Clamp1"]<PCR_Data["GC_Clamp2"],PCR_Data["GC_Clamp1"],PCR_Data["GC_Clamp2"])
PCR_Data["GC_ClampMax"] = np.where(PCR_Data["GC_Clamp1"]>PCR_Data["GC_Clamp2"],PCR_Data["GC_Clamp1"],PCR_Data["GC_Clamp2"])

In [76]:
#Drop GC_CLamp columns used for analysis and primers because we are done pulling data from them
remove=["GC_Clamp1","GC_Clamp2","primer1","primer2","polymerase_name","cycles1","cycles3","HP_P1","HP_P2","Homodimer_tm1","Homodimer_tm2","Tm_p1_IDT","Tm_p2_IDT","primer1_GC","primer2_GC","P1_len","P2_len",'amtprimer1','amtprimer2']
PCR_Data.drop(remove,axis=1,inplace=True)
PCR_Data.head()

,temp1,melting_temp2,annealing_temp2,extension_temp2,cycles2,temp3,band_size,dna_amt,buffer,dmso_amount,...,Homodimer_minTm,MaxTm_IDT,MinTm_IDT,MaxGC,MinGC,MaxPlen,MinPlen,TotPrimer,GC_ClampMin,GC_ClampMax
0,98.0,98.0,58.0,72.0,35.0,72.0,1840.0,3.0,NaN,NaN,...,-55.773368,51.387895,47.132343,52.631579,38.095238,21,19,1.0,30,34
1,98.0,98.0,66.0,72.0,35.0,72.0,1423.0,3.0,NaN,NaN,...,-66.357220,53.493671,51.075794,58.823529,50.000000,20,17,1.0,30,32
2,98.0,98.0,67.0,72.0,35.0,72.0,2453.0,3.0,NaN,NaN,...,-45.030107,55.996572,52.940547,61.111111,55.000000,20,18,1.0,34,36

In [77]:
PCR_Data

,temp1,melting_temp2,annealing_temp2,extension_temp2,cycles2,temp3,band_size,dna_amt,buffer,dmso_amount,...,Homodimer_minTm,MaxTm_IDT,MinTm_IDT,MaxGC,MinGC,MaxPlen,MinPlen,TotPrimer,GC_ClampMin,GC_ClampMax
0,98.0,98.0,58.0,72.0,35.0,72.0,1840.0,3.0,NaN,NaN,...,-55.773368,51.387895,47.132343,52.631579,38.095238,21,19,1.0,30,34
1,98.0,98.0,66.0,72.0,35.0,72.0,1423.0,3.0,NaN,NaN,...,-66.357220,53.493671,51.075794,58.823529,50.000000,20,17,1.0,30,32
2,98.0,98.0,67.0,72.0,35.0,72.0,2453.0,3.0,NaN,NaN,...,-45.030107,55.996572,52.940547,61.111111,55.000000,20,18,1.0,34,36

In [78]:
PCR_Data['dna_amt'].min()

3.0

In [79]:
#Move outcome to the first position
PCR_Data=PCR_Data[['temp1', 'melting_temp2',
       'annealing_temp2', 'extension_temp2', 'cycles2', 'temp3',
       'band_size', 'dna_amt','t1(sec)', 'melting_t2(sec)',
       'annealing_t3(sec)', 'extension_t4(sec)', 't5(sec)', 'Tm_p1_p3orig', 'Tm_p2_p3orig', 'Tm_p1_p3',
       'Tm_p2_p3', 'Tm_p1_BSU', 'Tm_p2_BSU', 'Tm_dif_IDT',
       'HPin_Tm_Max', 'Heterodimer_tm', 'Homodimer_maxTm', 'GC_ClampMin',
       'GC_ClampMax', 'MaxTm_IDT','MinTm_IDT','MaxGC','MinGC','MaxPlen','MinPlen','TotPrimer']]

In [80]:
import datetime
now = datetime.datetime.now()
print("Current date")
now = str(now)
date = now.split(" ")
print(date[0])

Current date
2021-04-12

In [81]:
engfname = "Vanessa_Dumont_redo41921_"+date[0]+"_myeng110120_predictoutcome.csv"#0706 noticed error in primer feat eng
print(engfname)

Vanessa_Dumont_redo41921_2021-04-12_myeng110120_predictoutcome.csv

In [82]:
cleanedF = os.path.join("C:/Users/jpcor/GoogleDrive/Data Science/Clauset's/PCR Analysis/CleanedData/TestData/", engfname)  
PCR_Data.to_csv(cleanedF,index=False)

In [ ]:
#Drop HP_P1 and HP_P2
remove=["HP_P1","HP_P2"]
PCR_Data.drop(remove,axis=1,inplace=True)
PCR_Data.head()
remove=["Homodimer_tm1","Homodimer_tm2"]
PCR_Data.drop(remove,axis=1,inplace=True)

In [43]:
PCR_Data

,temp1,melting_temp2,annealing_temp2,extension_temp2,cycles2,temp3,band_size,dna_amt,t1(sec),melting_t2(sec),...,Homodimer_maxTm,GC_ClampMin,GC_ClampMax,MaxTm_IDT,MinTm_IDT,MaxGC,MinGC,MaxPlen,MinPlen,TotPrimer
0,98.0,98.0,58.0,72.0,35.0,72.0,1840.0,3.0,30.0,10.0,...,0,30,34,50.109406,45.962008,52.631579,38.095238,21,19,0.4
1,98.0,98.0,66.0,72.0,35.0,72.0,1300.0,3.0,30.0,10.0,...,0,33,41,52.208138,49.222177,75.000000,62.500000,16,16,0.4
2,98.0,98.0,65.0,72.0,35.0,72.0,3000.0,3.0,30.0,10.0,...,0,32,36,54.292811,51.435699,50.000000,43.478261,23,20,0.4
3,98.0,98.0,67.0,72.0,35.0,72.0,3000.0,3.0,30.0,10.0,...,0,34,36,54.743410,51.564502,61.111111,55.000000,20,18,0.4
4,98.0,98.0,66.0,72.0,35.0,72.0,8300.0,3.0,30.0,10.0,...,0,30,31,54.277472,52.496881,60.000000,47.619048,21,20,0.4
5,98.0,98.0,66.0,72.0,35.0,72.0,1423.0,3.0,30.0,10.0,...,0,30,32,52.246785,49.615785,58.823529,50.000000,20,17,0.4